language: php

php:
  - 5.6
  - 7
  - 7.1
  - hhvm

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: hhvm
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=highest
    - php: 7
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: hhvm
      env: dependencies=highest
  allow_failures:
    - php: hhvm
    - php: 7.1

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
